services:
  db_development:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: 'development'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5433:5432'
    volumes:
      - dev-v:/var/lib/postgresql/data

  db_testing:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: 'testing'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5434:5432'
    volumes:
      - test-v:/var/lib/postgresql/data

volumes:
  dev-v:
  test-v: